# Variables
$mainMod = SUPER
$left = h
$down = j
$up = k
$right = l

$terminal = ghostty
$browser = brave
$filemanager = dolphin
$launcher = rofi -show drun -run-command "uwsm app -- {cmd}"
$screenlocker = hyprlock

# XWayland apps fix
exec-once = xrdb ~/.config/hypr/xresources

# Sources
source=~/.config/hypr/bindings.conf
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/settings.conf
source=~/.config/hypr/windowRules.conf
