windowrule {
  name = windowrule-1
  tag = +noOpacity
  no_initial_focus = on
  match:class = Unity
}

windowrule {
  name = windowrule-2
  tag = +noOpacity
  match:class = gimp
}

windowrule {
  name = windowrule-3
  tag = +noOpacity
  match:class = krita
}

windowrule {
  name = windowrule-4
  tag = +noOpacity
  match:class = (?:pinta|com.github.PintaProject.Pinta)
}

windowrule {
  name = windowrule-5
  tag = +noOpacity
  match:class = org.godotengine.Editor
}

windowrule {
  name = windowrule-6
  opacity = 1 override
  match:tag = noOpacity
}

windowrule {
  name = windowrule-7
  float = on
  match:class = pcmanfm-qt
  match:title = Search Files
}

windowrule {
  name = windowrule-8
  workspace = 2
  match:class = steam.*
  match:title = (?!notificationtoast).*
}

windowrule {
  name = windowrule-9
  workspace = 6
  match:class = brave-browser
}

windowrule {
  name = windowrule-10
  workspace = 10
  match:class = Spotify
}

windowrule {
  name = windowrule-11
  tag = +contextMenu
  match:float = 1
  match:class = ^$
  match:title = ^$
}

windowrule {
  name = windowrule-12
  no_blur = on
  rounding = 0 override
  opacity = 1 override
  match:tag = contextMenu
}

windowrule {
  name = FloatingWindows
  match:float = 1
  persistent_size = on
}

windowrule {
  name = OnlyOfficeNoShadow
  match:class = ONLYOFFICE
  no_shadow = on
}

windowrule {
  name = OnlyOfficeContextMenu
  match:class = ONLYOFFICE
  match:float = 1
  tag = +contextMenu
}

windowrule {
  name = PcManFmCopyFilesFloat
  match:class = pcmanfm-qt
  match:initial_title = Copy Files
  float = on
  persistent_size = on
}

windowrule {
  name = PcManFmRemovableMediumFloat
  match:class = pcmanfm-qt
  match:initial_title = Removable medium is inserted
  float = on
  persistent_size = on
}
