# Rules
windowrule {
  name = ContextMenu
  match:tag = contextMenu
  no_blur = on
  rounding = 0 override
  opacity = 1 override
}

windowrule {
  name = NoOpacity
  match:tag = noOpacity
  opacity = 1 override
}

# Remember floating window size
windowrule {
  name = FloatingWindows
  match:float = 1
  persistent_size = on
}

# Tag assignements
windowrule {
  name = ContextMenuUpgrade
  tag = +contextMenu
  match:float = 1
  match:class = ^$
  match:title = ^$
}

windowrule {
  name = Unity
  match:class = Unity
  tag = +noOpacity
  no_initial_focus = on
}

windowrule {
  name = Gimp
  match:class = gimp
  tag = +noOpacity
}

windowrule {
  name = Krita
  match:class = krita
  tag = +noOpacity
}

windowrule {
  name = Pinta
  match:class = (?:pinta|com.github.PintaProject.Pinta)
  tag = +noOpacity
}

windowrule {
  name = Godot
  match:class = org.godotengine.Editor
  tag = +noOpacity
}

windowrule {
  name = OnlyOfficeContextMenu
  match:class = ONLYOFFICE
  match:float = 1
  tag = +contextMenu
}

# Workspace assignements
windowrule {
  name = Brave
  workspace = 6
  match:class = brave-browser
}

windowrule {
  name = Feishin
  workspace = 10
  match:class = feishin
}

# Other
windowrule {
  name = OnlyOfficeNoShadow
  match:class = ONLYOFFICE
  no_shadow = on
}

windowrule {
  name = PcManFmFloat
  match:class = pcmanfm-qt
  match:initial_title = Copy Files|Move Files|Search Files|Removable medium is inserted
  float = on
}

windowrule {
  name = EngrampaExtract
  match:class = engrampa
  match:initial_title = Extract
  float = on
}
