# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Prompt theme
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/zsh/p10k.conf.zsh
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true # disable p9k

# Syntax highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Auto-suggestion
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
ZSH_AUTOSUGGEST_STRATEGY=(history match_prev_cmd completion)

# Auto-complete
autoload -Uz compinit; compinit
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}" "r:|=*" "l:|=* r:|=*"
zstyle ":completion:*" menu select
_comp_options+=(globdots)

# jeffreytse/zsh-vi-mode
source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
autoload -U history-search-end

# Misc
setopt auto_cd
WORDCHARS=

# NVM
if [[ -r /usr/share/nvm/init-nvm.sh ]]; then
  source /usr/share/nvm/init-nvm.sh
fi


### Env ###
export PATH=$PATH:~/.local/bin:~/.cargo/bin
export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="nvim +Man!"
export KEYTIMEOUT=1
export TERM=xterm-256color
export DOTNET_CLI_UI_LANGUAGE=en
export DOCKER_HOST=unix:///var/run/docker.sock


### Aliases ###
# Git
source ~/.zsh/omz.lib.git.zsh
source ~/.zsh/omz.git.plugin.zsh
alias gf="gfa" # gf="git fetch" +a="--all --prune"

# General
alias sudo="sudo "
alias open="xdg-open"
alias o="open"
alias vim="nvim"
alias so="source"
alias h="history"
alias he="$EDITOR $HISTFILE" # History edit
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias treeg="tree --gitignore"

# System dependent
alias ph="grep -i installed /var/log/pacman.log" # pacman history
alias bc="bc -q" # Basic calculator
alias cal="cal -w" # Calendar

# Eza
alias eza="eza --git"
alias ls="eza --icons"
alias l="eza -laF"
alias ll="eza -laFG"

# Other programs
alias nightlight="redshift -x && redshift -O $1"
alias cmatrix="cmatrix -abu6"
alias waybar="killall waybar; waybar"
alias dunst-restart="killall dunst; notify-send 'dunst restarted'"


### Local file ###
if [[ -r ~/.config/zsh/local.zsh ]]; then
  source ~/.config/zsh/local.zsh
fi
